
package Vista.RRHH;

import Vista.RRHH.CONSULTAR_RRHH;

public class MENU_JEFE_DE_RRHH extends javax.swing.JFrame {

    
    public MENU_JEFE_DE_RRHH() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ComboMenuSalir = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ComboMenuConsultar = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        ComboMenuSalir.setSelected(true);
        ComboMenuSalir.setText("SALIR");
        ComboMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(ComboMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registros");

        ComboMenuConsultar.setSelected(true);
        ComboMenuConsultar.setText("Consultar Registros");
        ComboMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMenuConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(ComboMenuConsultar);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Configurar usuario y/o contraseña");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMenuConsultarActionPerformed
        CONSULTAR_RRHH fr=new CONSULTAR_RRHH();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_ComboMenuConsultarActionPerformed

    private void ComboMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ComboMenuSalirActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        MODIFICAR_USUARIO fr=new MODIFICAR_USUARIO();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_JEFE_DE_RRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_JEFE_DE_RRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_JEFE_DE_RRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_JEFE_DE_RRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_JEFE_DE_RRHH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem ComboMenuConsultar;
    private javax.swing.JCheckBoxMenuItem ComboMenuSalir;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
