/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.ADMINISTRADOR.MODIFICAR_ADMIN;
import Vista.ADMINISTRADOR.REGISTRAR;
import Vista.LOGISTICA.MODIFICAR_INVENTARIO;
import Vista.LOGISTICA.MODIFICAR_USUARIO;
import Vista.LOGISTICA.REGISTRAR_INVENTARIO;
import Vista.RRHH.CONSULTAR_RRHH;

/**
 *
 * @author USUARIO
 */
public class MENU extends javax.swing.JFrame {

    String mo;
    public MENU() {
               
    }

    public MENU(String mo) {
       initComponents();
       setLocationRelativeTo(null);
       this.mo=mo;
        if(mo.equalsIgnoreCase("ADMINISTRADOR")){
            
        } else if(mo.equalsIgnoreCase("JEFE DE COMPRAS")){
            MenuRRHH.setEnabled(false);
            SubModificarU.setEnabled(false);
            SubRegistroU.setEnabled(false);
        } else if(mo.equalsIgnoreCase("JEFE DE RR.HH")){
            MenuLogistica.setEnabled(false);
            SubModificarU.setEnabled(false);
            SubRegistroU.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        MenuConfig = new javax.swing.JMenu();
        SubRegistroU = new javax.swing.JCheckBoxMenuItem();
        SubModificarU = new javax.swing.JCheckBoxMenuItem();
        SubModificarCon = new javax.swing.JCheckBoxMenuItem();
        MenuRRHH = new javax.swing.JMenu();
        SubConsultarPlanilla = new javax.swing.JCheckBoxMenuItem();
        MenuLogistica = new javax.swing.JMenu();
        SubRegistrarInventario = new javax.swing.JCheckBoxMenuItem();
        SubModificarInventario = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/Gestion_de_inventarios.png"))); // NOI18N

        jMenuBar1.setPreferredSize(new java.awt.Dimension(334, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/cerrar-sesion.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N

        jCheckBoxMenuItem7.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Salir");
        jCheckBoxMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/SignOut_icon-icons.com_74704.png"))); // NOI18N
        jCheckBoxMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem7);

        jMenuBar1.add(jMenu1);

        MenuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/engranaje.png"))); // NOI18N
        MenuConfig.setText("Configuracion de usuarios");
        MenuConfig.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N

        SubRegistroU.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubRegistroU.setSelected(true);
        SubRegistroU.setText("Registrar usuarios");
        SubRegistroU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/registro.png"))); // NOI18N
        SubRegistroU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubRegistroUActionPerformed(evt);
            }
        });
        MenuConfig.add(SubRegistroU);

        SubModificarU.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubModificarU.setSelected(true);
        SubModificarU.setText("Modificar datos de los usuarios");
        SubModificarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/editar user.png"))); // NOI18N
        SubModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubModificarUActionPerformed(evt);
            }
        });
        MenuConfig.add(SubModificarU);

        SubModificarCon.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubModificarCon.setSelected(true);
        SubModificarCon.setText("Modificar contraseña");
        SubModificarCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/password_5167.png"))); // NOI18N
        SubModificarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubModificarConActionPerformed(evt);
            }
        });
        MenuConfig.add(SubModificarCon);

        jMenuBar1.add(MenuConfig);

        MenuRRHH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/portapapeles.png"))); // NOI18N
        MenuRRHH.setText("RR. HH");
        MenuRRHH.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N

        SubConsultarPlanilla.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubConsultarPlanilla.setSelected(true);
        SubConsultarPlanilla.setText("Consultar planilla");
        SubConsultarPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/consultante.png"))); // NOI18N
        SubConsultarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubConsultarPlanillaActionPerformed(evt);
            }
        });
        MenuRRHH.add(SubConsultarPlanilla);

        jMenuBar1.add(MenuRRHH);

        MenuLogistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/import.png"))); // NOI18N
        MenuLogistica.setText("Logistica");
        MenuLogistica.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        MenuLogistica.setHideActionText(true);

        SubRegistrarInventario.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubRegistrarInventario.setSelected(true);
        SubRegistrarInventario.setText("Registrar productos");
        SubRegistrarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/cargo.png"))); // NOI18N
        SubRegistrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubRegistrarInventarioActionPerformed(evt);
            }
        });
        MenuLogistica.add(SubRegistrarInventario);

        SubModificarInventario.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SubModificarInventario.setSelected(true);
        SubModificarInventario.setText("Modificar datos de los productos ");
        SubModificarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMAGENES_PROYECTO_USUARIOS/editar.png"))); // NOI18N
        SubModificarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubModificarInventarioActionPerformed(evt);
            }
        });
        MenuLogistica.add(SubModificarInventario);

        jMenuBar1.add(MenuLogistica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubRegistrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubRegistrarInventarioActionPerformed
        REGISTRAR_INVENTARIO fr=new REGISTRAR_INVENTARIO();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubRegistrarInventarioActionPerformed

    private void SubModificarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubModificarInventarioActionPerformed
        MODIFICAR_INVENTARIO fr=new MODIFICAR_INVENTARIO();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubModificarInventarioActionPerformed

    private void SubModificarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubModificarConActionPerformed
        MODIFICAR_USUARIO fr=new MODIFICAR_USUARIO();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubModificarConActionPerformed

    private void SubRegistroUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubRegistroUActionPerformed
        REGISTRAR fr=new REGISTRAR();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubRegistroUActionPerformed

    private void SubModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubModificarUActionPerformed
        MODIFICAR_ADMIN fr=new MODIFICAR_ADMIN();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubModificarUActionPerformed

    private void SubConsultarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubConsultarPlanillaActionPerformed
        CONSULTAR_RRHH fr=new CONSULTAR_RRHH();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_SubConsultarPlanillaActionPerformed

    private void jCheckBoxMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jCheckBoxMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenu MenuLogistica;
    private javax.swing.JMenu MenuRRHH;
    private javax.swing.JCheckBoxMenuItem SubConsultarPlanilla;
    private javax.swing.JCheckBoxMenuItem SubModificarCon;
    private javax.swing.JCheckBoxMenuItem SubModificarInventario;
    private javax.swing.JCheckBoxMenuItem SubModificarU;
    private javax.swing.JCheckBoxMenuItem SubRegistrarInventario;
    private javax.swing.JCheckBoxMenuItem SubRegistroU;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
